version: '3.8'

services:
  telegram-to-mail:
    build: .
    container_name: telegram-to-mail
    restart: unless-stopped
    
    # 环境变量：所有敏感信息都集中在这里！
    environment:
      # --- Telegram Userbot 配置 ---
      - API_ID=12345678
      - API_HASH=0123456789abcdef0123456789abcdef
      - SESSION_NAME=telegram-to-mail
      - TARGET_CHAT_IDS=12345678,-12345678 # 多个ID用逗号隔开
      - TO_EMAIL=your_target_email@example.com

      # --- msmtp (邮件发送) 配置 ---
      - MSMTP_HOST=smtp.qq.com
      - MSMTP_PORT=587 # 可选，默认为 587
      - MSMTP_FROM=your_sender_email@qq.com
      - MSMTP_USER=your_sender_email@qq.com
      - MSMTP_PASSWORD=your_app_specific_password # 通常是应用专用密码

    # 数据卷挂载
    volumes:
      # 只需持久化 session 文件即可
      - ./session_data:/app

    # 第一次运行时需要交互式输入验证码
    stdin_open: true
    tty: true
