version: '3.8'

services:
  telegram-forwarder:
    # 构建当前目录下的 Dockerfile
    build: .
    # 给容器起一个好记的名字
    container_name: telegram_forwarder
    # 重启策略：除非手动停止，否则总是在崩溃后重启
    restart: unless-stopped
    
    # 环境变量：所有敏感信息都在这里！
    environment:
      # --- 请在这里填写您的配置 ---
      - API_ID=12345678
      - API_HASH=0123456789abcdef0123456789abcdef
      - SESSION_NAME=my_telegram_session
      - TARGET_CHAT_IDS=12345678,-12345678 # 多个ID用逗号隔开
      - TO_EMAIL=your_email@example.com

    # 数据卷挂载
    volumes:
      # 将本地的 msmtp 配置文件挂载到容器的系统位置 (只读)
      - ./msmtprc:/etc/msmtprc:ro
      # 将 session 文件保存在本地，防止容器重建后丢失登录状态
      - ./session_data:/app

    # 第一次运行时需要交互式输入验证码
    stdin_open: true
    tty: true
